[workspace]
members = [
  "crates/*",
  "examples/*",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
gausplat-importer = {path = "crates/gausplat-importer"}
gausplat-renderer = {path = "crates/gausplat-renderer"}
gausplat-trainer = {path = "crates/gausplat-trainer"}

anyhow = {version = "1.0.89", default-features = false}
burn = {git = "https://github.com/tracel-ai/burn", rev = "e804f90473e06f9c32e7788a6e89cd999a855740", default-features = false}
burn-jit = {git = "https://github.com/tracel-ai/burn", rev = "e804f90473e06f9c32e7788a6e89cd999a855740", default-features = false}
burn-tensor = {git = "https://github.com/tracel-ai/burn", rev = "e804f90473e06f9c32e7788a6e89cd999a855740", default-features = false}
bytemuck = {version = "1.17.0", default-features = false}
dashmap = {version = "6.0.1", default-features = false}
divan = {version = "0.1.14", default-features = false}
humansize = {version = "2.1.3", default-features = false}
image = {version = "0.25.2", default-features = false}
indexmap = {version = "2.5.0", default-features = false}
kdam = {version = "0.5.2", default-features = false}
lazy_static = {version = "1.5.0", default-features = false}
log = {version = "0.4.22", default-features = false}
pretty_env_logger = {version = "0.5.0", default-features = false}
rand = {version = "0.8.5", default-features = false}
rand_distr = {version = "0.4.3", default-features = false}
rayon = {version = "1.10.0", default-features = false}
thiserror = {version = "1.0.64", default-features = false}

[patch.crates-io]
wgpu = {git = "https://github.com/AsherJingkongChen/wgpu", rev = "a5652bd47759ccfb861f9d70fe3e0d3a132f327a"}

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
panic = "abort"
strip = true
