[workspace]
members = [
  "crates/*",
  "examples/*",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
gausplat-importer = {path = "crates/gausplat-importer"}
gausplat-renderer = {path = "crates/gausplat-renderer"}
gausplat-trainer = {path = "crates/gausplat-trainer"}

anyhow = {version = "1.0.86", default-features = false}
burn = {version = "0.14.0", default-features = false}
bytemuck = {version = "1.17.0", default-features = false}
cubecl = {version = "0.2.0", default-features = false}
dashmap = {version = "6.0.1", default-features = false}
image = {version = "0.25.2", default-features = false}
lazy_static = {version = "1.5.0", default-features = false}
rand = {version = "0.8.5", default-features = false}
rand_distr = {version = "0.4.3", default-features = false}
rayon = {version = "1.10.0", default-features = false}
thiserror = {version = "1.0.63", default-features = false}

[patch.crates-io]
naga = {git = "https://github.com/AsherJingkongChen/wgpu.git", rev = "13700d630b532f63b72e7147bf54e5c3fc40567c"}

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
panic = "abort"
strip = true
