[workspace]
members = [
  "crates/*",
  "examples/*",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
anyhow = {version = "1.0.86", default-features = false, features = ["std"]}
bytemuck = {version = "1.16.1", default-features = false}
dashmap = {version = "6.0.1", default-features = false, features = ["rayon"]}
image = {version = "0.25.1", default-features = false}
rayon = {version = "1.10.0", default-features = false}

[profile.dev]
opt-level = 1
